"""create a unique constraint for tags

Revision ID: 1bd0bfc8ad8e
Revises: 2ef374a160a1
Create Date: 2022-08-15 22:24:06.720103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bd0bfc8ad8e"
down_revision = "2ef374a160a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_user_tag", "tag", ["tag", "owner_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_user_tag", "tag", type_="unique")
    # ### end Alembic commands ###
