"""change resource model to include s3 bucket location link

Revision ID: 221686bb3774
Revises: 2c771ada2136
Create Date: 2022-08-21 08:27:03.136614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221686bb3774'
down_revision = '2c771ada2136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('s3_bucket_link', sa.String(length=300), nullable=True))
    op.alter_column('resource', 'link',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource', 'link',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('resource', 's3_bucket_link')
    # ### end Alembic commands ###
