"""test change in resourc emodel

Revision ID: 35e409aec757
Revises: cb698d35e939
Create Date: 2022-08-15 19:45:47.049428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35e409aec757"
down_revision = "cb698d35e939"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
