"""completely change resource_tag to model

Revision ID: 3aef741ee669
Revises: dd94ce0c2ee5
Create Date: 2022-08-16 21:25:27.508312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aef741ee669'
down_revision = 'dd94ce0c2ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_tag',
    sa.Column('resource_tag_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('resource_tag_id'),
    sa.UniqueConstraint('resource_id', 'tag_id', name='_resource_tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_tag')
    # ### end Alembic commands ###
