"""completely change resource_tag to model

Revision ID: af886e11c1b7
Revises: 3aef741ee669
Create Date: 2022-08-17 08:46:45.932347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af886e11c1b7"
down_revision = "3aef741ee669"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "user_role", sa.Enum("user", "admin", name="userrole"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_role")
    # ### end Alembic commands ###
