"""First migration - create basic tables

Revision ID: b50bdadac915
Revises: 
Create Date: 2022-08-14 19:14:58.879827

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b50bdadac915"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("company", sa.String(length=50), nullable=True),
        sa.Column("job_position", sa.String(length=50), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "resource",
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("author", sa.String(length=150), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=1, scale=1), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("read", "pending", "dropped", name="resourcestatus"),
            nullable=False,
        ),
        sa.Column(
            "created_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    op.create_table(
        "tag",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_table(
        "resource_tag",
        sa.Column("resource_tag_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resource.resource_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.tag_id"],
        ),
        sa.PrimaryKeyConstraint("resource_tag_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_tag")
    op.drop_table("tag")
    op.drop_table("resource")
    op.drop_table("user")
    # ### end Alembic commands ###
