"""change resource model to include s3 bucket location link, change column name

Revision ID: ceffe7958a60
Revises: 221686bb3774
Create Date: 2022-08-21 09:21:44.626527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ceffe7958a60"
down_revision = "221686bb3774"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource", sa.Column("file_url", sa.String(length=300), nullable=True)
    )
    op.drop_column("resource", "s3_bucket_link")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource",
        sa.Column(
            "s3_bucket_link", sa.VARCHAR(length=300), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("resource", "file_url")
    # ### end Alembic commands ###
