"""change resource-tag table

Revision ID: d55f1d80effa
Revises: 1bd0bfc8ad8e
Create Date: 2022-08-16 20:44:00.290877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d55f1d80effa"
down_revision = "1bd0bfc8ad8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "resource_tag", "resource_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "resource_tag", "tag_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource_tag", "tag_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "resource_tag", "resource_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
