"""change resource-tag table, unique constraint

Revision ID: dd94ce0c2ee5
Revises: d55f1d80effa
Create Date: 2022-08-16 21:00:58.188120

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd94ce0c2ee5"
down_revision = "d55f1d80effa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource_tag",
        sa.Column("resource_tag_id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resource.resource_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.tag_id"],
        ),
        sa.PrimaryKeyConstraint("resource_tag_id"),
        sa.UniqueConstraint("resource_id", "tag_id", name="_resource_tag"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource_tag")
    # ### end Alembic commands ###
