"""test change in resourc emodel

Revision ID: ee590c396f2f
Revises: 35e409aec757
Create Date: 2022-08-15 19:53:29.181636

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee590c396f2f"
down_revision = "35e409aec757"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("resource", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
